# Generated by Django 3.2.5 on 2021-08-03 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='pick_playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.pickplaylist'),
        ),
    ]
