# Generated by Django 3.2.5 on 2021-08-03 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_youtubevideo_pick_playlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickplaylist',
            old_name='youtube_link',
            new_name='youtube_id',
        ),
        migrations.RenameField(
            model_name='youtubevideo',
            old_name='link',
            new_name='youtube_id',
        ),
    ]
