# Generated by Django 3.2.5 on 2021-08-03 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210803_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickpair',
            name='pick',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.youtubevideo', verbose_name='User pick'),
        ),
    ]
