# Generated by Django 3.2.5 on 2021-08-03 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_picksessionround_pick_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickpair',
            name='pick_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.picksession'),
        ),
    ]
